metadata: {}
pipelines:
  blis:
    envs:
    - host
    path: pipelines/blis
    stages:
    - run
  docker-data-science:
    envs:
    - host
    path: pipelines/docker-data-science
    stages:
    - setup
    - analyze
    - generate-figures
popperized:
- github/popperized
