metadata: {}
pipelines:
  blis:
    envs:
    - host
    path: pipelines/blis
    stages:
    - run
  docker-data-science:
    envs:
    - host
    path: pipelines/docker-data-science
    stages:
    - setup
    - analyze
    - generate-figures
  datapackage:
    envs:
    - host
    path: pipelines/datapackage
    stages:
    - run
    - update-datapackage
popperized:
- github/popperized
