metadata: {}
pipelines:
  blis:
    envs:
    - host
    path: pipelines/blis
    stages:
    - run
  envvar-param:
    envs:
    - host
    path: pipelines/envvar-param
    stages:
    - run
popperized:
- github/popperized
